const DadosDeProjetos = [
    {
        id : 1,
        foto : 'Sorveteria',
        tituloEn: 'Project - Sorveteria',
        tituloPT: 'Projeto - Sorveteria',
        TextoEn: 'Project created by DevMedia,  developed by my self using the technologies below',
        TextoPT: 'Projeto proposto pela DevMedia,  desenvolvido por mim utilizando as tecnologias abaixo',
        Link: 'https://sorveteria-alpha.vercel.app',
        JS : true,
        CSS : true,
        HTML : true,
        REACT : true,
    },
    {
        id : 2,
        foto : 'Sorveteria',
        tituloEn: 'Project - Sorveteria',
        tituloPT: 'Projeto - Sorveteria',
        TextoEn: 'Project created by DevMedia,  developed by my self using the technologies below',
        TextoPT: 'Projeto proposto pela DevMedia,  desenvolvido por mim utilizando as tecnologias abaixo',
        Link: 'https://sorveteria-alpha.vercel.app',
        JS : true,
        CSS : false,
        HTML : true,
        REACT : true,
    },{
        id : 3,
        foto : 'Sorveteria',
        tituloEn: 'Project - Sorveteria',
        tituloPT: 'Projeto - Sorveteria',
        TextoEn: 'Project created by DevMedia,  developed by my self using the technologies below',
        TextoPT: 'Projeto proposto pela DevMedia,  desenvolvido por mim utilizando as tecnologias abaixo',
        Link: 'https://sorveteria-alpha.vercel.app',
        JS : true,
        CSS : true,
        HTML : true,
        REACT : true,
    },{
        id : 4,
        foto : 'Sorveteria',
        tituloEn: 'Project - Sorveteria',
        tituloPT: 'Projeto - Sorveteria',
        TextoEn: 'Project created by DevMedia,  developed by my self using the technologies below',
        TextoPT: 'Projeto proposto pela DevMedia,  desenvolvido por mim utilizando as tecnologias abaixo',
        Link: 'https://sorveteria-alpha.vercel.app',
        JS : true,
        CSS : true,
        HTML : true,
        REACT : true,
    },{
        id : 5,
        foto : 'Sorveteria',
        tituloEn: 'Project - Sorveteria',
        tituloPT: 'Projeto - Sorveteria',
        TextoEn: 'Project created by DevMedia,  developed by my self using the technologies below',
        TextoPT: 'Projeto proposto pela DevMedia,  desenvolvido por mim utilizando as tecnologias abaixo',
        Link: 'https://sorveteria-alpha.vercel.app',
        JS : true,
        CSS : true,
        HTML : true,
        REACT : true,
    },{
        id : 6,
        foto : 'Sorveteria',
        tituloEn: 'Project - Sorveteria',
        tituloPT: 'Projeto - Sorveteria',
        TextoEn: 'Project created by DevMedia,  developed by my self using the technologies below',
        TextoPT: 'Projeto proposto pela DevMedia,  desenvolvido por mim utilizando as tecnologias abaixo',
        Link: 'https://sorveteria-alpha.vercel.app',
        JS : true,
        CSS : true,
        HTML : true,
        REACT : true,
    }
];

export default DadosDeProjetos;